# Generated by Django 5.0.6 on 2025-10-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='professional_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
