# Generated by Django 5.0.6 on 2025-10-07 19:50

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appointment_professional_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_range',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'scheduled')), expressions=[(models.F('time_range'), '&&'), (models.F('professional'), '=')], name='appointment_prof_overlap'),
        ),
    ]
