# Generated by Django 5.0.6 on 2025-10-10 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appointment_time_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizacionProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_rut', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('num_employees', models.IntegerField(blank=True, null=True)),
                ('company_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('service_type_required', models.CharField(blank=True, max_length=100, null=True)),
                ('preference_modality', models.CharField(blank=True, max_length=50, null=True)),
                ('type_of_attention', models.CharField(blank=True, max_length=100, null=True)),
                ('service_frequency', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=15)),
                ('inclusive_orientation', models.BooleanField(default=False)),
                ('base_disease', models.CharField(max_length=100)),
                ('disability', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('consultation_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('preference_modality', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_focus', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PsicologoProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=15)),
                ('specialty', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50)),
                ('main_focus', models.CharField(max_length=100)),
                ('therapeutic_techniques', models.TextField()),
                ('style_of_attention', models.TextField()),
                ('attention_schedule', models.CharField(max_length=255)),
                ('work_modality', models.CharField(max_length=50)),
                ('certificates', models.FileField(upload_to='certificates/')),
                ('inclusive_orientation', models.BooleanField(default=False)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('curriculum_vitae', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('cases_attended', models.IntegerField(default=0, editable=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='specialty',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('profesional', 'Profesional'), ('organizacion', 'Organización'), ('admin', 'Administrador')], default='paciente', max_length=20),
        ),
    ]
