# Generated by Django 5.0.6 on 2025-10-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_organizacionprofile_pacienteprofile_psicologoprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteprofile',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacienteprofile',
            name='gender',
            field=models.CharField(default='Otro', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacienteprofile',
            name='nationality',
            field=models.CharField(default='Chileno', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psicologoprofile',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psicologoprofile',
            name='gender',
            field=models.CharField(default='Otro', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psicologoprofile',
            name='nationality',
            field=models.CharField(default='Chileno', max_length=50),
            preserve_default=False,
        ),
    ]
