# Generated by Django 5.0.6 on 2025-10-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_migrate_specialties_to_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologoprofile',
            name='specialty_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='psicologoprofile',
            name='specialty',
            field=models.CharField(choices=[('psiquiatria', 'Psiquiatría'), ('psicologia_clinica', 'Psicología Clínica'), ('infanto_juvenil', 'Psicología Infantil y Adolescente'), ('pareja_familia', 'Terapia de Pareja y Familia'), ('neuropsicologia', 'Neuropsicología'), ('sexologia_clinica', 'Sexología Clínica'), ('adicciones', 'Adicciones'), ('gerontopsicologia', 'Psicología Geriátrica'), ('psicologia_salud', 'Psicología de la Salud'), ('evaluacion_psicologica', 'Evaluación/Peritaje Psicológico'), ('psicologia_educativa', 'Psicología Educativa'), ('otro', 'Otro')], default='psicologia_clinica', max_length=50),
        ),
    ]
