# Generated by Django 5.0.6 on 2025-10-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_psicologoprofile_specialty_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='modality',
            field=models.CharField(blank=True, choices=[('Presencial', 'Presencial'), ('Online', 'Online')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
