# Generated by Django 5.0.6 on 2025-10-16 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_appointment_modality_appointment_reason'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
