# Generated by Django 5.0.6 on 2025-10-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='supabase_uid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
