# Generated by Django 4.2.2 on 2025-10-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='zoom_join_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='zoom_start_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
