# Generated by Django 4.2.2 on 2025-10-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_appointment_zoom_join_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologoprofile',
            name='zoom_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologoprofile',
            name='zoom_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologoprofile',
            name='zoom_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
