# Generated by Django 4.2.2 on 2025-10-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_psicologoprofile_zoom_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='zoom_join_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='zoom_start_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
