# Generated by Django 5.2.7 on 2025-11-12 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customuser_supabase_uid'),
        ('api', '0014_alter_appointment_zoom_join_url_and_more'),
    ]

    operations = [
    ]
