# Generated by Django 5.0.6 on 2025-11-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_20251116_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologoprofile',
            name='session_price',
            field=models.PositiveIntegerField(blank=True, help_text='Precio por sesión en CLP', null=True),
        ),
    ]
