# Generated by Django 5.0.6 on 2025-11-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_psicologoprofile_session_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologoprofile',
            name='attention_schedule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
