# Generated by Django 5.2.7 on 2025-11-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_supportticket_fecha_respuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologoprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
