# Generated by Django 5.0.6 on 2025-11-20 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_appointment_notes_appointmentnote'),
        ('api', '0017_alter_psicologoprofile_attention_schedule'),
        ('api', '0018_psicologoprofile_is_available'),
    ]

    operations = [
    ]
