"""
Django settings for psicolink_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import sys
from pathlib import Path
from decouple import config, Config, RepositoryEnv  # ← AGREGADO AQUÍ
from datetime import timedelta
import os

MP_ACCESS_TOKEN = config("MP_ACCESS_TOKEN")
WEBHOOK_URL_BASE = config("WEBHOOK_URL_BASE")
FRONTEND_URL = config("FRONTEND_URL")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dzjw*a--g8b%gtenq!)f53&35$@p+!_lcoq-!zw7m6otpxdm^5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'backend-psicolink.onrender.com']


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'api',
    'payments',
    'django_filters',
    'django.contrib.postgres',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ]
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8100", # Para desarrollo local de Ionic
    "http://127.0.0.1:8100",
    "https://capstone-psicolink.onrender.com", 
    "https://capstone-psicolink-1.onrender.com",
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8100",
    "https://capstone-psicolink.onrender.com",
    "https://capstone-psicolink-1.onrender.com", 
]

ROOT_URLCONF = 'psicolink_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'psicolink_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
            'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
            'NAME': config('DB_NAME', default='postgres'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST'),
            'PORT': config('DB_PORT', cast=int, default=6543),
            #'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', cast=int, default=0),  # 0 = sin conexiones persistentes
            'DISABLE_SERVER_SIDE_CURSORS': True,
            'OPTIONS': {
                'sslmode': 'require',   # Obligatorio con Supabase
            },
        },
        
        
    #    'TEST': {
    #        'NAME': config('TEST_DB_NAME', default=None),  # base de test ya creada
    #    
    #},
    
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'api.CustomUser'

# ---- Configuración de reglas del negocio ----
ROLE_DURATION_LIMITS = {
    'psiquiatria': (15, 60),
    'psicologia_clinica': (30, 120),
    'infanto_juvenil': (45, 90),
    'pareja_familia': (50, 90),
    'neuropsicologia': (45, 120),
    'sexologia_clinica': (45, 90),
    'adicciones': (45, 90),
    'gerontopsicologia': (45, 90),
    'psicologia_salud': (45, 90),
    'evaluacion_psicologica': (30, 120),
    'psicologia_educativa': (45, 90),
    'default': (15, 120),
}

SIMPLE_JWT = {
    # Aumenta el tiempo de vida del Access Token (ej: de 5 minutos a 30 minutos)
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30), 
    
    # El Refresh Token (usado para obtener nuevos Access Tokens)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7), 
}

SUPABASE_URL = config("SUPABASE_URL", default="")
SUPABASE_SERVICE_ROLE = config("SUPABASE_SERVICE_ROLE", default="")
SUPABASE_ANON_KEY = config("SUPABASE_ANON_KEY", default="")

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

#LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'

#USE_I18N = True

#USE_TZ = True

# 1. Zona horaria de la aplicación: Santiago (Chile)
TIME_ZONE = 'America/Santiago' 

# 2. Idioma de la aplicación: Español de Chile
LANGUAGE_CODE = 'es-cl' 

# 3. Activa el soporte para internacionalización
USE_I18N = True

# 4. Activa el soporte para zonas horarias (MANDATORIO para el manejo correcto de horarios)
USE_TZ = True 


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#ZOOM LOCAL TEST
ZOOM_CLIENT_ID = config("ZOOM_CLIENT_ID")
ZOOM_CLIENT_SECRET = config("ZOOM_CLIENT_SECRET")
ZOOM_REDIRECT_URI = config("ZOOM_REDIRECT_URI")


